### ISSUE TITLE
翻译：Dialogue abstraction

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#1]
源文档地址：https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/documentation/dialogue.md

**Comment by Weiting-Zhang** [comment]
翻译认领

**Comment by JasinYip** [comment]
> 翻译认领

收到！谢谢 @Weiting-Zhang

**Comment by JasinYip** [comment]
Done.
