### ISSUE TITLE
翻译：api/isolate

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#12]
https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/api/isolate.md

**Comment by Tina92** [comment]
@JasinYip  翻译认领

**Comment by JasinYip** [comment]
> @JasinYip 翻译认领

收到！谢谢 @Tina92

**Comment by xunge0613** [comment]
认领校对 @JasinYip 

话说原文里的 API 部分好像木有在译文中看到呢
http://cyclejs.cn/api/isolate.html

**Comment by JasinYip** [comment]
> 认领校对 @JasinYip
> 
> 话说原文里的 API 部分好像木有在译文中看到呢
> http://cyclejs.cn/api/isolate.html

意思是文档落后了是吗？

**Comment by Tina92** [comment]
@xunge0613 https://github.com/CyclejsCN/cyclejs.cn/pull/31 已补上 API 部分，谢谢指出
