### ISSUE TITLE
翻译：api/jsonp

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#14]
https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/api/jsonp.md

**Comment by eryue0220** [comment]
认领 @JasinYip

**Comment by JasinYip** [comment]
> 认领 @JasinYip

收到！谢谢 @eryue0220

**Comment by xunge0613** [comment]
校对认领 @JasinYip
