### ISSUE TITLE
翻译：api/most-run

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#15]
https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/api/most-run.md

**Comment by YESUNFEI** [comment]
认领 @JasinYip

**Comment by JasinYip** [comment]
> 认领 @JasinYip

收到！谢谢 @YESUNFEI ！

**Comment by tso-si** [comment]
提前认领校对@JasinYip

**Comment by JasinYip** [comment]
> 提前认领校对@JasinYip

@imnotnerd 已经翻译完了，你可以开始校对啦

**Comment by xunge0613** [comment]
@JasinYip 认领校对~

**Comment by JasinYip** [comment]
Done.
