### ISSUE TITLE
翻译：api/run

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#16]
https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/api/run.md

**Comment by SZzzzz** [comment]
认领 @JasinYip

**Comment by JasinYip** [comment]
> 认领 @JasinYip

收到，感谢 @SZzzzz ！

**Comment by linxiangjun** [comment]
@JasinYip  认领校对

**Comment by JasinYip** [comment]
> @JasinYip 认领校对

收到！谢谢 @linxiangjun

**Comment by linxiangjun** [comment]
校对已完成，写了些建议，请查验。 @JasinYip @SZzzzz

**Comment by JasinYip** [comment]
Done.
