### ISSUE TITLE
翻译：api/rxjs-run

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#17]
https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/api/rxjs-run.md

**Comment by yct21** [comment]
认领 @JasinYip

**Comment by JasinYip** [comment]
> 认领 @JasinYip

收到！谢谢 @yct21

**Comment by tso-si** [comment]
认领校对@JasinYip

**Comment by JasinYip** [comment]
> 认领校对@JasinYip

收到，感谢 @imnotnerd

**Comment by tso-si** [comment]
@JasinYip   lgtm.翻译地很好@yct21
