### ISSUE TITLE
翻译：Streams

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#2]
源文件地址：https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/documentation/streams.md

**Comment by panricas** [comment]
@JasinYip 认领，Ricas Pan

**Comment by JasinYip** [comment]
> @JasinYip 认领，Ricas Pan

收到！辛苦 @panricas ~

**Comment by jasonxia23** [comment]
@JasinYip 认领校对

**Comment by JasinYip** [comment]
> @JasinYip 认领校对

收到，谢谢 @jasonxia23

**Comment by JasinYip** [comment]
Done.
