### ISSUE TITLE
翻译：Basic examples

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#3]
源文件地址：https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/documentation/basic-examples.md

**Comment by Tina92** [comment]
@JasinYip 认领

**Comment by JasinYip** [comment]
> @JasinYip 认领

收到！辛苦 @Tina92

**Comment by yangzj1992** [comment]
认领校对

**Comment by JasinYip** [comment]
> 认领校对

收到！感谢 @yangzj1992 ~~~

**Comment by yangzj1992** [comment]
@JasinYip  @Tina92  已校对完成，可进行查收或二校。有些地方翻译待商榷，可讨论。

**Comment by yangzj1992** [comment]
https://github.com/CyclejsCN/cyclejs.cn/pull/22/files

**Comment by JasinYip** [comment]
> @JasinYip @Tina92 已校对完成，可进行查收或二校。有些地方翻译待商榷，可讨论。

辛苦啦！校对得很认真！辛苦 @Tina92 改一下哈

**Comment by Tina92** [comment]
@yangzj1992 不好意思，我没有看到你提出修改意见的 review。你是提在我的 pr 下面吗？？
@JasinYip

**Comment by yangzj1992** [comment]
@Tina92 在 PR 下面.我之前 评论在 file change 里的。

**Comment by Tina92** [comment]
@yangzj1992 谢谢校对，辛苦！

**Comment by JasinYip** [comment]
Done.
