### ISSUE TITLE
翻译：Model-View-Intent

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#4]
源文件地址：https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/documentation/model-view-intent.md

**Comment by yangzj1992** [comment]
认领。

**Comment by JasinYip** [comment]
> 认领。

收到！辛苦 @yangzj1992

**Comment by ethansure** [comment]
认领校对

**Comment by JasinYip** [comment]
> 认领校对

收到！谢谢 @ethansure

**Comment by yangzj1992** [comment]
@ethansure 意见很棒，谢谢。  @JasinYip  已完成校对修改

**Comment by JasinYip** [comment]
Done.
