### ISSUE TITLE
翻译：Components

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#5]
源文件地址：https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/documentation/components.md

**Comment by yoyoyohamapi** [comment]
认领@JaisnYip

**Comment by yoyoyohamapi** [comment]
认领 @JasinYip

**Comment by JasinYip** [comment]
> 认领 @JasinYip

收到！辛苦啦 @yoyoyohamapi

**Comment by JasinYip** [comment]
Done.
