### ISSUE TITLE
翻译：首页

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#7]
源文件地址：https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/index.md

**Comment by zhengxiaowai** [comment]
@JasinYip 认领
BY 正小歪

**Comment by JasinYip** [comment]
> @JasinYip 认领
> BY 正小歪

收到！辛苦~~ @zhengxiaowai

**Comment by jasonxia23** [comment]
@JasinYip 认领校对

**Comment by JasinYip** [comment]
> @JasinYip 认领校对

收到！感谢 @jasonxia23
