### ISSUE TITLE
翻译：api/dom

### ISSUE THREAD

**Issue by JasinYip** [CyclejsCN/cyclejs.cn#8]
源文件地址：https://github.com/CyclejsCN/cyclejs.cn/blob/master/content/api/dom.md

**Comment by jasonxia23** [comment]
@JasinYip 认领，jasonxia23

**Comment by JasinYip** [comment]
> @JasinYip 认领，jasonxia23

收到！辛苦了 @jasonxia23

**Comment by JasinYip** [comment]
将由 @xunge0613 来进行校对~
